### ISSUE TITLE
R&D: Encrypt datacenter credentials on database

### ISSUE THREAD

**Issue by purehyperbole** [ernestio/ernest#167]
Currently datacenter passwords are stored on datacenter-store in plain text. 

To improve security, we should look at some form of encryption for the datacenter passwords. Hashing won't be sufficient as we need to use the password, so a crptographic function would be best. Either scrypt(used on user-store) or gpg could work.

It may also be worth looking at encrypting/password protecting NATS traffic too, to prevent eavesdropping.

**Comment by adriacidre** [comment]
In order to successfully store secrets any service should be able to decrypt them, otherwise they will be passed around in plain through the nats bus and anybody can catch them, and just read them.

Actually the most feasible way to do it is to have a **shared key** between all services, so bus messages will show an encrypted secret at the same time any ernest service can decrypt it.

In order to accomplish that we will need:

- [ ] ernest setup : should be able to ask for and pass to every container an environment variable with the ernest_secret_key so all passwords are encrypted using that key
- [ ] ernest-vagrant : should be setting this environment variable so it works also on a dev env.
- [ ] datacenter-store : should store datacenter sensible data encrypted.
- [ ] all-all-aws-connector : should be able to decrypt this data.
- [ ] vcloud-connectors : requiring access to this data should implement that decryption.

Additionally we will need to [secure nats](https://github.com/nats-io/gnatsd#securing-nats) :

- [ ] Password protect nats, using bcrypt.
- [ ] Enable nats TLS
- [ ] Use a self signed certificate to run ernest under a valid https
