### ISSUE TITLE
Datacenter credential update required after upgrade from 1.11.0 to 1.12.0

### ISSUE THREAD

**Issue by reidjc** [ernestio/ernest#249]
After upgrading from 1.11.0 to 1.12.0 I needed to reapply my datacenter credentials before I could make changes to my existing services.

Upgrade process was:

docker-compose down
git checkout docker-compose.yml
git checkout config/nginx/ernest.local
git checkout master
git pull
./setup

**Comment by purehyperbole** [comment]
This occurs because running `git checkout docker-compose.yml` and `./setup` clears the `TOKEN` and `CRYPTO_KEY` variables on `docker-compose.yml`.

Moving generated variables like the crypto key to the ernest config.json will avoid the upgrade process overwriting the variables. Any service that needs those keys will have to request them over nats via config store

**Comment by adriacidre** [comment]
It doesn't makes any sense to me have to run all these commands to upgrade ernest.

```
docker-compose down
git checkout docker-compose.yml
git checkout config/nginx/ernest.local
git checkout master
git pull
./setup
```

Having an specific command `./upgrade` should be enough to run all these commands and recover `ERNEST_CRYPTO_KEY` and `JWT_TOKEN` so the user is not able to set up a different values.
